import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";
import { Cart } from "../Context/CartContext";

function Layout({ title, children }) {
  const { state } = useContext(Cart);
  return (
    <div>
      <Head>
        <title>{title ? title : "Thang-Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col bg-blue-100 justify-between">
        <header className="shadow-md">
          <nav className="flex h-12 items-center px-4 justify-between">
            <Link href="/" className="text-lg font-bold">
              Ecommerce
            </Link>
            <div className="">
              <Link href="/cart" className="p-2">
                Cart
                {state.cartItems.length > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {state.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </Link>
              <Link href="/login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center shadow-inner items-center">
          <p>Copyright @2022 Thang-Ecommerce</p>
        </footer>
      </div>
    </div>
  );
}
export default Layout;
